### ISSUE TITLE
.from sometimes does not accept user names or time periods

### ISSUE THREAD

**Issue by overcast07** [ishwi/discordBot#32]
Documentation for .from:

> **Name:** Artist from a country
> **Description:** Your top artist that are from a specific country
> **Aliases:** .from
> **Usage:** .from *country* *[d,w,m,q,s,y,a]* *username*** 
>     If username its not specified it defaults to you
>     If timeframe its not specified it defaults to All-Time
>     Country must come in the full name format or in the ISO 3166-1 alpha-2/alpha-3 format

I tried using `.from japan a [username]`, `.from japan [username]`, `.from GB a [username]`, and `.from GB [username]` and the queries didn't work, I think it tried to interpret the whole line as the country name in each case. `.from JA a` doesn't work but `.from japan a` does. This seems to be a combination of two issues:
* ISO names are treated differently to English names
* Usernames are not interpreted correctly unless they're Discord \@mentions

(the documentation also has some errors; it should say "your top artists", it uses "its" instead of "is", and there are two extra asterisks)

**Comment by ishwi** [comment]
Thanks for taking the time to report this issue.  

The from command only accepts usernames with the @ format to avoid confusion between the country parsing and the user parsing. Same thing as in the .favs, .wk, .wka... because you can't really tell if what you wrote is the username or the part of text that the command accepts, or at least I coudn't find a way to do that.

If the issue happens with the @ then there's probably something wrong. 
And finally  I think `.from JA a` doesn't work because the [ISO 2 code from Japan is JP, not JA].(https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)

**Comment by overcast07** [comment]
Thanks for noticing that, I misremembered. Testing with JP returns the same results as for Japan.

Maybe the command could accept usernames with the user#0000 format? Obviously there would be an advantage to allowing the command to be used without notifying the other user.

**Comment by ishwi** [comment]
I added that possibility, and included some documentation to the commands that have limited mention functionality.
